<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'nome' => 'Arroz Branco',
                'descricao' => 'Arroz branco tipo 1, embalagem de 1kg.',
                'categoria' => 'Alimentos',
                'marca' => 'Tio João',
                'unidade_medida' => 'kg',
                'preco_venda' => 15.99,
                'preco_custo' => 10.99,
                'estoque_atual' => 100,
                'estoque_minimo' => 20,
                'estoque_maximo' => 200,
                'peso' => 1000, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567890',
                'sku' => 'ARROZ-TJ-1KG',
                'ncm' => '1006.30.10',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2023-01-01',
                'data_validade' => '2025-01-01',
                'data_entrada_estoque' => '2023-01-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/arroz.jpg',
                'status' => 'ativo',
                'observacoes' => 'Produto sensível à umidade. Armazenar em local seco.',
            ],
            [
                'nome' => 'Feijão Preto',
                'descricao' => 'Feijão preto tipo 1, embalagem de 1kg.',
                'categoria' => 'Alimentos',
                'marca' => 'Kicaldo',
                'unidade_medida' => 'kg',
                'preco_venda' => 8.49,
                'preco_custo' => 5.99,
                'estoque_atual' => 75,
                'estoque_minimo' => 15,
                'estoque_maximo' => 150,
                'peso' => 1000, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567891',
                'sku' => 'FEIJAO-KC-1KG',
                'ncm' => '0713.33.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2023-02-15',
                'data_validade' => '2024-12-31',
                'data_entrada_estoque' => '2023-02-20',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 7.99,
                'data_inicio_promocao' => '2023-10-01',
                'data_fim_promocao' => '2023-10-31',
                'imagem' => 'https://example.com/feijao.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local fresco.',
            ],
            [
                'nome' => 'Açúcar Refinado',
                'descricao' => 'Açúcar refinado, embalagem de 1kg.',
                'categoria' => 'Alimentos',
                'marca' => 'União',
                'unidade_medida' => 'kg',
                'preco_venda' => 4.99,
                'preco_custo' => 3.49,
                'estoque_atual' => 50,
                'estoque_minimo' => 10,
                'estoque_maximo' => 100,
                'peso' => 1000, // em gramas
                'altura' => 15, // em cm
                'largura' => 8, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567892',
                'sku' => 'ACUCAR-UN-1KG',
                'ncm' => '1701.99.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 10, // em dias
                'data_fabricacao' => '2023-03-10',
                'data_validade' => '2025-03-10',
                'data_entrada_estoque' => '2023-03-15',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/acucar.jpg',
                'status' => 'ativo',
                'observacoes' => 'Produto solúvel. Evitar contato com água.',
            ],
            [
                'nome' => 'Macarrão Espaguete',
                'descricao' => 'Macarrão espaguete, embalagem de 500g.',
                'categoria' => 'Alimentos',
                'marca' => 'Renata',
                'unidade_medida' => 'kg',
                'preco_venda' => 6.99,
                'preco_custo' => 4.50,
                'estoque_atual' => 120,
                'estoque_minimo' => 30,
                'estoque_maximo' => 250,
                'peso' => 500, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567893',
                'sku' => 'MACARRAO-RN-500G',
                'ncm' => '1902.11.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 10, // em dias
                'data_fabricacao' => '2023-04-01',
                'data_validade' => '2025-04-01',
                'data_entrada_estoque' => '2023-04-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/macarrao.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco e arejado.',
            ],
            [
                'nome' => 'Óleo de Soja',
                'descricao' => 'Óleo de soja, embalagem de 900ml.',
                'categoria' => 'Alimentos',
                'marca' => 'Liza',
                'unidade_medida' => 'litro',
                'preco_venda' => 8.99,
                'preco_custo' => 6.50,
                'estoque_atual' => 80,
                'estoque_minimo' => 20,
                'estoque_maximo' => 150,
                'peso' => 900, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567894',
                'sku' => 'OLEO-LZ-900ML',
                'ncm' => '1507.90.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2023-05-01',
                'data_validade' => '2024-05-01',
                'data_entrada_estoque' => '2023-05-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 7.99,
                'data_inicio_promocao' => '2023-11-01',
                'data_fim_promocao' => '2023-11-30',
                'imagem' => 'https://example.com/oleo.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local fresco e longe do calor.',
            ],
            [
                'nome' => 'Farinha de Trigo',
                'descricao' => 'Farinha de trigo, embalagem de 1kg.',
                'categoria' => 'Alimentos',
                'marca' => 'Dona Benta',
                'unidade_medida' => 'kg',
                'preco_venda' => 5.49,
                'preco_custo' => 3.99,
                'estoque_atual' => 60,
                'estoque_minimo' => 15,
                'estoque_maximo' => 120,
                'peso' => 1000, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567895',
                'sku' => 'FARINHA-DB-1KG',
                'ncm' => '1101.00.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2023-06-01',
                'data_validade' => '2025-06-01',
                'data_entrada_estoque' => '2023-06-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/farinha.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco e arejado.',
            ],
            [
                'nome' => 'Leite Integral',
                'descricao' => 'Leite integral, embalagem de 1 litro.',
                'categoria' => 'Bebidas',
                'marca' => 'Piracanjuba',
                'unidade_medida' => 'litro',
                'preco_venda' => 4.99,
                'preco_custo' => 3.50,
                'estoque_atual' => 150,
                'estoque_minimo' => 50,
                'estoque_maximo' => 300,
                'peso' => 1000, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567896',
                'sku' => 'LEITE-PI-1L',
                'ncm' => '0401.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 3, // em dias
                'data_fabricacao' => '2023-07-01',
                'data_validade' => '2023-09-01',
                'data_entrada_estoque' => '2023-07-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 4.49,
                'data_inicio_promocao' => '2023-12-01',
                'data_fim_promocao' => '2023-12-31',
                'imagem' => 'https://example.com/leite.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar após abertura.',
            ],
            [
                'nome' => 'Café Torrado',
                'descricao' => 'Café torrado e moído, embalagem de 500g.',
                'categoria' => 'Alimentos',
                'marca' => 'Melitta',
                'unidade_medida' => 'kg',
                'preco_venda' => 12.99,
                'preco_custo' => 9.50,
                'estoque_atual' => 40,
                'estoque_minimo' => 10,
                'estoque_maximo' => 80,
                'peso' => 500, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567897',
                'sku' => 'CAFE-ME-500G',
                'ncm' => '0901.21.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 10, // em dias
                'data_fabricacao' => '2023-08-01',
                'data_validade' => '2025-08-01',
                'data_entrada_estoque' => '2023-08-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/cafe.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco e arejado.',
            ],
            [
                'nome' => 'Sabonete Líquido',
                'descricao' => 'Sabonete líquido para mãos, embalagem de 250ml.',
                'categoria' => 'Higiene',
                'marca' => 'Dove',
                'unidade_medida' => 'litro',
                'preco_venda' => 10.99,
                'preco_custo' => 7.50,
                'estoque_atual' => 30,
                'estoque_minimo' => 10,
                'estoque_maximo' => 60,
                'peso' => 250, // em gramas
                'altura' => 15, // em cm
                'largura' => 8, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567898',
                'sku' => 'SABONETE-DV-250ML',
                'ncm' => '3401.30.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2023-09-01',
                'data_validade' => '2025-09-01',
                'data_entrada_estoque' => '2023-09-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 9.99,
                'data_inicio_promocao' => '2024-01-01',
                'data_fim_promocao' => '2024-01-31',
                'imagem' => 'https://example.com/sabonete.jpg',
                'status' => 'ativo',
                'observacoes' => 'Manter fora do alcance de crianças.',
            ],
            [
                'nome' => 'Detergente Líquido',
                'descricao' => 'Detergente líquido, embalagem de 500ml.',
                'categoria' => 'Limpeza',
                'marca' => 'Ypê',
                'unidade_medida' => 'litro',
                'preco_venda' => 3.99,
                'preco_custo' => 2.50,
                'estoque_atual' => 100,
                'estoque_minimo' => 20,
                'estoque_maximo' => 200,
                'peso' => 500, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567899',
                'sku' => 'DETERGENTE-YP-500ML',
                'ncm' => '3402.20.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2023-10-01',
                'data_validade' => '2025-10-01',
                'data_entrada_estoque' => '2023-10-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/detergente.jpg',
                'status' => 'ativo',
                'observacoes' => 'Evitar contato com os olhos.',
            ],
            [
                'nome' => 'Shampoo Anticaspa',
                'descricao' => 'Shampoo anticaspa, embalagem de 300ml.',
                'categoria' => 'Higiene',
                'marca' => 'Head & Shoulders',
                'unidade_medida' => 'litro',
                'preco_venda' => 25.99,
                'preco_custo' => 18.50,
                'estoque_atual' => 45,
                'estoque_minimo' => 15,
                'estoque_maximo' => 90,
                'peso' => 300, // em gramas
                'altura' => 22, // em cm
                'largura' => 8, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567900',
                'sku' => 'SHAMPOO-HS-300ML',
                'ncm' => '3305.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2023-11-01',
                'data_validade' => '2025-11-01',
                'data_entrada_estoque' => '2023-11-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 22.99,
                'data_inicio_promocao' => '2024-02-01',
                'data_fim_promocao' => '2024-02-29',
                'imagem' => 'https://example.com/shampoo.jpg',
                'status' => 'ativo',
                'observacoes' => 'Uso externo. Evitar contato com os olhos.',
            ],
            [
                'nome' => 'Pasta de Dente',
                'descricao' => 'Pasta de dente com flúor, embalagem de 90g.',
                'categoria' => 'Higiene',
                'marca' => 'Colgate',
                'unidade_medida' => 'kg',
                'preco_venda' => 8.49,
                'preco_custo' => 5.99,
                'estoque_atual' => 120,
                'estoque_minimo' => 30,
                'estoque_maximo' => 250,
                'peso' => 90, // em gramas
                'altura' => 18, // em cm
                'largura' => 5, // em cm
                'comprimento' => 3, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567901',
                'sku' => 'PASTA-CG-90G',
                'ncm' => '3306.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2023-12-01',
                'data_validade' => '2025-12-01',
                'data_entrada_estoque' => '2023-12-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/pasta.jpg',
                'status' => 'ativo',
                'observacoes' => 'Manter fora do alcance de crianças.',
            ],
            [
                'nome' => 'Desinfetante',
                'descricao' => 'Desinfetante multiuso, embalagem de 1 litro.',
                'categoria' => 'Limpeza',
                'marca' => 'Veja',
                'unidade_medida' => 'litro',
                'preco_venda' => 12.99,
                'preco_custo' => 9.50,
                'estoque_atual' => 50,
                'estoque_minimo' => 10,
                'estoque_maximo' => 100,
                'peso' => 1000, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567902',
                'sku' => 'DESINFETANTE-VJ-1L',
                'ncm' => '3402.20.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2024-01-01',
                'data_validade' => '2026-01-01',
                'data_entrada_estoque' => '2024-01-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 10.99,
                'data_inicio_promocao' => '2024-03-01',
                'data_fim_promocao' => '2024-03-31',
                'imagem' => 'https://example.com/desinfetante.jpg',
                'status' => 'ativo',
                'observacoes' => 'Não misturar com outros produtos químicos.',
            ],
            [
                'nome' => 'Sabão em Pó',
                'descricao' => 'Sabão em pó concentrado, embalagem de 1kg.',
                'categoria' => 'Limpeza',
                'marca' => 'OMO',
                'unidade_medida' => 'kg',
                'preco_venda' => 15.99,
                'preco_custo' => 11.50,
                'estoque_atual' => 80,
                'estoque_minimo' => 20,
                'estoque_maximo' => 160,
                'peso' => 1000, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567903',
                'sku' => 'SABAO-OMO-1KG',
                'ncm' => '3402.20.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2024-02-01',
                'data_validade' => '2026-02-01',
                'data_entrada_estoque' => '2024-02-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/sabao.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco e arejado.',
            ],
            [
                'nome' => 'Cerveja Lager',
                'descricao' => 'Cerveja lager, garrafa de 600ml.',
                'categoria' => 'Bebidas',
                'marca' => 'Brahma',
                'unidade_medida' => 'litro',
                'preco_venda' => 4.99,
                'preco_custo' => 3.50,
                'estoque_atual' => 200,
                'estoque_minimo' => 50,
                'estoque_maximo' => 400,
                'peso' => 600, // em gramas
                'altura' => 30, // em cm
                'largura' => 8, // em cm
                'comprimento' => 8, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567904',
                'sku' => 'CERVEJA-BR-600ML',
                'ncm' => '2203.00.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 3, // em dias
                'data_fabricacao' => '2024-03-01',
                'data_validade' => '2025-03-01',
                'data_entrada_estoque' => '2024-03-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 3.99,
                'data_inicio_promocao' => '2024-04-01',
                'data_fim_promocao' => '2024-04-30',
                'imagem' => 'https://example.com/cerveja.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar antes de consumir.',
            ],
            [
                'nome' => 'Refrigerante Cola',
                'descricao' => 'Refrigerante cola, garrafa de 2 litros.',
                'categoria' => 'Bebidas',
                'marca' => 'Coca-Cola',
                'unidade_medida' => 'litro',
                'preco_venda' => 7.99,
                'preco_custo' => 5.50,
                'estoque_atual' => 150,
                'estoque_minimo' => 40,
                'estoque_maximo' => 300,
                'peso' => 2000, // em gramas
                'altura' => 35, // em cm
                'largura' => 12, // em cm
                'comprimento' => 12, // em cm
                'volume' => 2, // em litros
                'codigo_barras' => '7891234567905',
                'sku' => 'REFRI-CC-2L',
                'ncm' => '2202.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2024-04-01',
                'data_validade' => '2025-04-01',
                'data_entrada_estoque' => '2024-04-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/refrigerante.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar antes de consumir.',
            ],
            [
                'nome' => 'Suco de Laranja',
                'descricao' => 'Suco de laranja integral, caixa de 1 litro.',
                'categoria' => 'Bebidas',
                'marca' => 'Del Valle',
                'unidade_medida' => 'litro',
                'preco_venda' => 6.49,
                'preco_custo' => 4.50,
                'estoque_atual' => 100,
                'estoque_minimo' => 20,
                'estoque_maximo' => 200,
                'peso' => 1000, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567906',
                'sku' => 'SUCO-DV-1L',
                'ncm' => '2009.12.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2024-05-01',
                'data_validade' => '2025-05-01',
                'data_entrada_estoque' => '2024-05-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 5.99,
                'data_inicio_promocao' => '2024-05-15',
                'data_fim_promocao' => '2024-05-31',
                'imagem' => 'https://example.com/suco.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar após abertura.',
            ],
            [
                'nome' => 'Água Mineral',
                'descricao' => 'Água mineral sem gás, garrafa de 500ml.',
                'categoria' => 'Bebidas',
                'marca' => 'Crystal',
                'unidade_medida' => 'litro',
                'preco_venda' => 2.49,
                'preco_custo' => 1.50,
                'estoque_atual' => 300,
                'estoque_minimo' => 100,
                'estoque_maximo' => 600,
                'peso' => 500, // em gramas
                'altura' => 20, // em cm
                'largura' => 8, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567907',
                'sku' => 'AGUA-CR-500ML',
                'ncm' => '2201.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 3, // em dias
                'data_fabricacao' => '2024-06-01',
                'data_validade' => '2025-06-01',
                'data_entrada_estoque' => '2024-06-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/agua.jpg',
                'status' => 'ativo',
                'observacoes' => 'Conservar em local fresco.',
            ],
            [
                'nome' => 'Chocolate ao Leite',
                'descricao' => 'Chocolate ao leite, barra de 100g.',
                'categoria' => 'Alimentos',
                'marca' => 'Lacta',
                'unidade_medida' => 'kg',
                'preco_venda' => 5.99,
                'preco_custo' => 4.00,
                'estoque_atual' => 200,
                'estoque_minimo' => 50,
                'estoque_maximo' => 400,
                'peso' => 100, // em gramas
                'altura' => 15, // em cm
                'largura' => 8, // em cm
                'comprimento' => 2, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567908',
                'sku' => 'CHOCOLATE-LT-100G',
                'ncm' => '1806.31.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2024-07-01',
                'data_validade' => '2025-07-01',
                'data_entrada_estoque' => '2024-07-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 4.99,
                'data_inicio_promocao' => '2024-06-01',
                'data_fim_promocao' => '2024-06-30',
                'imagem' => 'https://example.com/chocolate.jpg',
                'status' => 'ativo',
                'observacoes' => 'Conservar em local fresco e seco.',
            ],
            [
                'nome' => 'Biscoito Recheado',
                'descricao' => 'Biscoito recheado de chocolate, pacote de 130g.',
                'categoria' => 'Alimentos',
                'marca' => 'Trakinas',
                'unidade_medida' => 'kg',
                'preco_venda' => 4.99,
                'preco_custo' => 3.50,
                'estoque_atual' => 150,
                'estoque_minimo' => 40,
                'estoque_maximo' => 300,
                'peso' => 130, // em gramas
                'altura' => 20, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567909',
                'sku' => 'BISCOITO-TK-130G',
                'ncm' => '1905.31.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2024-08-01',
                'data_validade' => '2025-08-01',
                'data_entrada_estoque' => '2024-08-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/biscoito.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco e arejado.',
            ],
            [
                'nome' => 'Sabonete Barra',
                'descricao' => 'Sabonete barra hidratante, embalagem de 90g.',
                'categoria' => 'Higiene',
                'marca' => 'Nivea',
                'unidade_medida' => 'kg',
                'preco_venda' => 4.99,
                'preco_custo' => 3.50,
                'estoque_atual' => 120,
                'estoque_minimo' => 30,
                'estoque_maximo' => 250,
                'peso' => 90, // em gramas
                'altura' => 10, // em cm
                'largura' => 5, // em cm
                'comprimento' => 2, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567910',
                'sku' => 'SABONETE-NV-90G',
                'ncm' => '3401.11.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2024-09-01',
                'data_validade' => '2026-09-01',
                'data_entrada_estoque' => '2024-09-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 3.99,
                'data_inicio_promocao' => '2024-07-01',
                'data_fim_promocao' => '2024-07-31',
                'imagem' => 'https://example.com/sabonete-barra.jpg',
                'status' => 'ativo',
                'observacoes' => 'Uso externo. Evitar contato com os olhos.',
            ],
            [
                'nome' => 'Amaciante de Roupas',
                'descricao' => 'Amaciante de roupas concentrado, embalagem de 2 litros.',
                'categoria' => 'Limpeza',
                'marca' => 'Downy',
                'unidade_medida' => 'litro',
                'preco_venda' => 18.99,
                'preco_custo' => 13.50,
                'estoque_atual' => 60,
                'estoque_minimo' => 20,
                'estoque_maximo' => 120,
                'peso' => 2000, // em gramas
                'altura' => 30, // em cm
                'largura' => 12, // em cm
                'comprimento' => 10, // em cm
                'volume' => 2, // em litros
                'codigo_barras' => '7891234567911',
                'sku' => 'AMACIANTE-DW-2L',
                'ncm' => '3809.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2024-10-01',
                'data_validade' => '2026-10-01',
                'data_entrada_estoque' => '2024-10-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/amaciante.jpg',
                'status' => 'ativo',
                'observacoes' => 'Não misturar com outros produtos químicos.',
            ],
            [
                'nome' => 'Creme Dental Infantil',
                'descricao' => 'Creme dental infantil sem flúor, embalagem de 50g.',
                'categoria' => 'Higiene',
                'marca' => 'Colgate Kids',
                'unidade_medida' => 'kg',
                'preco_venda' => 7.99,
                'preco_custo' => 5.50,
                'estoque_atual' => 90,
                'estoque_minimo' => 20,
                'estoque_maximo' => 180,
                'peso' => 50, // em gramas
                'altura' => 15, // em cm
                'largura' => 5, // em cm
                'comprimento' => 3, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567912',
                'sku' => 'CREME-CGK-50G',
                'ncm' => '3306.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2024-11-01',
                'data_validade' => '2026-11-01',
                'data_entrada_estoque' => '2024-11-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 6.99,
                'data_inicio_promocao' => '2024-08-01',
                'data_fim_promocao' => '2024-08-31',
                'imagem' => 'https://example.com/creme-dental-infantil.jpg',
                'status' => 'ativo',
                'observacoes' => 'Manter fora do alcance de crianças.',
            ],
            [
                'nome' => 'Esponja de Aço',
                'descricao' => 'Esponja de aço para limpeza pesada, pacote com 3 unidades.',
                'categoria' => 'Limpeza',
                'marca' => 'Bombril',
                'unidade_medida' => 'unidade',
                'preco_venda' => 2.99,
                'preco_custo' => 1.99,
                'estoque_atual' => 250,
                'estoque_minimo' => 50,
                'estoque_maximo' => 500,
                'peso' => 100, // em gramas
                'altura' => 10, // em cm
                'largura' => 5, // em cm
                'comprimento' => 2, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567913',
                'sku' => 'ESPONJA-BB-3UN',
                'ncm' => '9603.90.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2024-12-01',
                'data_validade' => '2026-12-01',
                'data_entrada_estoque' => '2024-12-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/esponja.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco.',
            ],
            [
                'nome' => 'Papel Higiênico',
                'descricao' => 'Papel higiênico folha dupla, pacote com 4 rolos.',
                'categoria' => 'Higiene',
                'marca' => 'Neve',
                'unidade_medida' => 'unidade',
                'preco_venda' => 12.99,
                'preco_custo' => 9.50,
                'estoque_atual' => 180,
                'estoque_minimo' => 50,
                'estoque_maximo' => 360,
                'peso' => 500, // em gramas
                'altura' => 25, // em cm
                'largura' => 12, // em cm
                'comprimento' => 10, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567914',
                'sku' => 'PAPEL-HG-NV-4R',
                'ncm' => '4818.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2025-01-01',
                'data_validade' => '2027-01-01',
                'data_entrada_estoque' => '2025-01-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 10.99,
                'data_inicio_promocao' => '2024-09-01',
                'data_fim_promocao' => '2024-09-30',
                'imagem' => 'https://example.com/papel-higienico.jpg',
                'status' => 'ativo',
                'observacoes' => 'Armazenar em local seco e arejado.',
            ],
            [
                'nome' => 'Água Sanitária',
                'descricao' => 'Água sanitária, embalagem de 1 litro.',
                'categoria' => 'Limpeza',
                'marca' => 'Qboa',
                'unidade_medida' => 'litro',
                'preco_venda' => 5.99,
                'preco_custo' => 4.00,
                'estoque_atual' => 100,
                'estoque_minimo' => 20,
                'estoque_maximo' => 200,
                'peso' => 1000, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567915',
                'sku' => 'AGUA-QB-1L',
                'ncm' => '3808.91.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 7, // em dias
                'data_fabricacao' => '2025-02-01',
                'data_validade' => '2027-02-01',
                'data_entrada_estoque' => '2025-02-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/agua-sanitaria.jpg',
                'status' => 'ativo',
                'observacoes' => 'Não misturar com outros produtos químicos.',
            ],
            [
                'nome' => 'Cerveja Pilsen',
                'descricao' => 'Cerveja pilsen, lata de 350ml.',
                'categoria' => 'Bebidas',
                'marca' => 'Skol',
                'unidade_medida' => 'litro',
                'preco_venda' => 3.99,
                'preco_custo' => 2.50,
                'estoque_atual' => 400,
                'estoque_minimo' => 100,
                'estoque_maximo' => 800,
                'peso' => 350, // em gramas
                'altura' => 15, // em cm
                'largura' => 8, // em cm
                'comprimento' => 8, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567916',
                'sku' => 'CERVEJA-SK-350ML',
                'ncm' => '2203.00.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 3, // em dias
                'data_fabricacao' => '2025-03-01',
                'data_validade' => '2026-03-01',
                'data_entrada_estoque' => '2025-03-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 2.99,
                'data_inicio_promocao' => '2024-10-01',
                'data_fim_promocao' => '2024-10-31',
                'imagem' => 'https://example.com/cerveja-pilsen.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar antes de consumir.',
            ],
            [
                'nome' => 'Refrigerante Uva',
                'descricao' => 'Refrigerante sabor uva, garrafa de 1 litro.',
                'categoria' => 'Bebidas',
                'marca' => 'Fanta',
                'unidade_medida' => 'litro',
                'preco_venda' => 6.49,
                'preco_custo' => 4.50,
                'estoque_atual' => 150,
                'estoque_minimo' => 40,
                'estoque_maximo' => 300,
                'peso' => 1000, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567917',
                'sku' => 'REFRI-FT-1L',
                'ncm' => '2202.10.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2025-04-01',
                'data_validade' => '2026-04-01',
                'data_entrada_estoque' => '2025-04-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/refrigerante-uva.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar antes de consumir.',
            ],
            [
                'nome' => 'Suco de Maracujá',
                'descricao' => 'Suco de maracujá integral, caixa de 1 litro.',
                'categoria' => 'Bebidas',
                'marca' => 'Del Valle',
                'unidade_medida' => 'litro',
                'preco_venda' => 6.99,
                'preco_custo' => 4.99,
                'estoque_atual' => 120,
                'estoque_minimo' => 30,
                'estoque_maximo' => 240,
                'peso' => 1000, // em gramas
                'altura' => 25, // em cm
                'largura' => 10, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567918',
                'sku' => 'SUCO-DV-MR-1L',
                'ncm' => '2009.80.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora XYZ',
                'tempo_reposicao' => 5, // em dias
                'data_fabricacao' => '2025-05-01',
                'data_validade' => '2026-05-01',
                'data_entrada_estoque' => '2025-05-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => true,
                'preco_promocional' => 5.99,
                'data_inicio_promocao' => '2024-11-01',
                'data_fim_promocao' => '2024-11-30',
                'imagem' => 'https://example.com/suco-maracuja.jpg',
                'status' => 'ativo',
                'observacoes' => 'Refrigerar após abertura.',
            ],
            [
                'nome' => 'Água Tônica',
                'descricao' => 'Água tônica, garrafa de 350ml.',
                'categoria' => 'Bebidas',
                'marca' => 'Schweppes',
                'unidade_medida' => 'litro',
                'preco_venda' => 4.49,
                'preco_custo' => 3.00,
                'estoque_atual' => 200,
                'estoque_minimo' => 50,
                'estoque_maximo' => 400,
                'peso' => 350, // em gramas
                'altura' => 20, // em cm
                'largura' => 8, // em cm
                'comprimento' => 5, // em cm
                'volume' => 1, // em litros
                'codigo_barras' => '7891234567919',
                'sku' => 'AGUA-TONICA-SW-350ML',
                'ncm' => '2202.90.00',
                'icms' => 18.0,
                'ipi' => 0.0,
                'pis_cofins' => 9.25,
                'fornecedor' => 'Distribuidora ABC',
                'tempo_reposicao' => 3, // em dias
                'data_fabricacao' => '2025-06-01',
                'data_validade' => '2026-06-01',
                'data_entrada_estoque' => '2025-06-10',
                'garantia' => 0, // em meses
                'promocao_ativa' => false,
                'preco_promocional' => null,
                'data_inicio_promocao' => null,
                'data_fim_promocao' => null,
                'imagem' => 'https://example.com/agua-tonica.jpg',
                'status' => 'ativo',
                'observacoes' => 'Conservar em local fresco.',
            ]
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
